name: mind_set_go
description: "Routiner."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  date_picker_timeline: ^1.2.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16 
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
